#!/usr/bin/env php
<?php
/**
 * si tiene dudas sobre el codigo visite {@link  http://ccmvc.com} o contacte con <enyerverfranco@gmail.com>
 * el sitio del framework CcMvc Aun se encuentra en construccion
 * 
 */
include (dirname(__FILE__) . "/../vendor/autoload.php");
define('__DEBUNG_CONSOLE_', true);

$app = CcMvc::Start(dirname(__FILE__), "Enyerber Franco");
/**
 * indico que el controlador index/eliminar podra ser llamado mediante eliminar esto es solo para demostrar 
 * el enrutamiento manual CcMvc normalmente enruta automaticamente los controladores pero se puede 
 * se puede tomar el mando completamente si es nesesario similar a laravel 
 */
$app->Console($argv); // inica el funcionamiento del framework


