<?php return array (
  'AppPath' => 
  array (
    0 => 'E:\\www\\CcMvcProyect\\protected\\',
    1 => 1483552960,
  ),
  '/ccmvcproyect/favicon.ico' => 
  array (
    0 => 
    array (
      'type' => 'file',
      'Controller' => 'E:\\www\\CcMvcProyect\\favicon.ico',
    ),
    1 => 1483552961,
  ),
  'VersionCache' => '1.0.0.5',
  'ModifyTime' => '2016-12-13 12:18:54',
  'Cc\\Mvc\\SelectorControllers' => 
  array (
    0 => 
    array (
      'Cc\\Mvc\\Cindex' => 'E:\\www\\CcMvcProyect\\protected\\controllers\\Cindex.php',
    ),
    1 => 1484306334,
  ),
  'Cc\\Mvc\\SQLite3Cc\\Mvc\\DBtablatest' => 
  array (
    0 => 
    array (
      'colum' => 
      array (
        'id' => 
        array (
          'Type' => 'int',
          'KEY' => 'PRI',
          'Null' => '',
          'TypeName' => '',
          'Extra' => NULL,
          'Position' => 0,
        ),
        'campo1' => 
        array (
          'Type' => 'varchar(10)',
          'KEY' => '',
          'Null' => '',
          'TypeName' => '',
          'Extra' => NULL,
          'Position' => 1,
        ),
        'campo2' => 
        array (
          'Type' => 'varchar(60)',
          'KEY' => '',
          'Null' => '',
          'TypeName' => '',
          'Extra' => NULL,
          'Position' => 2,
        ),
        'campo3' => 
        array (
          'Type' => 'date
',
          'KEY' => '',
          'Null' => '',
          'TypeName' => '',
          'Extra' => NULL,
          'Position' => 3,
        ),
      ),
      'primary' => 
      array (
        0 => 'id',
      ),
      'autoinrement' => NULL,
      'Ttipe' => 'table',
      'tabla' => 'test',
      'typeDB' => 'sqlite',
      'OrderColum' => 
      array (
        1 => 'id',
        2 => 'campo1',
        3 => 'campo2',
        4 => 'campo3',
      ),
    ),
    1 => 1484306334,
  ),
);?>