<?php return array (
  'AppPath' => 
  array (
    0 => 'E:\\www\\CcMvcProyect\\protected\\',
    1 => 1482021957,
  ),
  'Cc\\Mvc\\SelectorControllers' => 
  array (
    0 => 
    array (
      'Cc\\Mvc\\Cindex' => 'E:\\www\\CcMvcProyect\\protected\\controllers\\Cindex.php',
    ),
    1 => 1482021958,
  ),
  'Cc\\Mvc\\SQLite3Cc\\Mvc\\DBtablatest' => 
  array (
    0 => 
    array (
      'colum' => 
      array (
        'id' => 
        array (
          'Type' => 'int',
          'KEY' => 'PRI',
          'Null' => '',
          'TypeName' => '',
          'Extra' => NULL,
          'Position' => 0,
        ),
        'campo1' => 
        array (
          'Type' => 'varchar(10)',
          'KEY' => '',
          'Null' => '',
          'TypeName' => '',
          'Extra' => NULL,
          'Position' => 1,
        ),
        'campo2' => 
        array (
          'Type' => 'varchar(60)',
          'KEY' => '',
          'Null' => '',
          'TypeName' => '',
          'Extra' => NULL,
          'Position' => 2,
        ),
        'campo3' => 
        array (
          'Type' => 'date
',
          'KEY' => '',
          'Null' => '',
          'TypeName' => '',
          'Extra' => NULL,
          'Position' => 3,
        ),
      ),
      'primary' => 
      array (
        0 => 'id',
      ),
      'autoinrement' => NULL,
      'Ttipe' => 'table',
      'tabla' => 'test',
      'typeDB' => 'sqlite',
      'OrderColum' => 
      array (
        1 => 'id',
        2 => 'campo1',
        3 => 'campo2',
        4 => 'campo3',
      ),
    ),
    1 => 1482021960,
  ),
  'VersionCache' => '1.0.0.5',
  'ModifyTime' => '2016-12-04 02:56:19',
  '/ccmvcproyect/src/css/styles.css' => 
  array (
    0 => 
    array (
      'type' => 'file',
      'Controller' => 'E:\\www\\CcMvcProyect\\src\\css\\styles.css',
      'RealFile' => 'E:\\www\\CcMvcProyect\\protected\\Cache\\Mincss\\src.css.styles.css',
    ),
    1 => 1482370953,
  ),
  '/ccmvcproyect/src/images/ccmvc-peque.png' => 
  array (
    0 => 
    array (
      'type' => 'file',
      'Controller' => 'E:\\www\\CcMvcProyect\\src\\images\\CcMvc-peque.png',
    ),
    1 => 1482022038,
  ),
  '/ccmvcproyect/src/images/ccmvc-peque.png?GDw=50COOKIE1360' => 
  array (
    0 => 
    array (
      'type' => 'file',
      'Controller' => 'E:\\www\\CcMvcProyect\\src\\images\\CcMvc-peque.png',
      'RealFile' => 'E:\\www\\CcMvcProyect\\protected\\Cache\\ImageGD\\w50h50csrc.images.CcMvc-peque.png',
      'GDmaxW' => '1360',
    ),
    1 => 1482022039,
  ),
  '/ccmvcproyect/src/images/ccmvc-peque.png?GDw=50&GDh=70COOKIE1024' => 
  array (
    0 => 
    array (
      'type' => 'file',
      'Controller' => 'E:\\www\\CcMvcProyect\\src\\images\\CcMvc-peque.png',
      'RealFile' => 'E:\\www\\CcMvcProyect\\protected\\Cache\\ImageGD\\w50h70csrc.images.CcMvc-peque.png',
      'GDmaxW' => '1024',
    ),
    1 => 1482511975,
  ),
  '/ccmvcproyect/src/fonts/glyphicons-halflings-regular.woff2' => 
  array (
    0 => 
    array (
      'type' => 'file',
      'Controller' => 'E:\\www\\\\CcMvcProyect\\src\\fonts\\glyphicons-halflings-regular.woff2',
    ),
    1 => 1482370953,
  ),
  '/ccmvcproyect/favicon.ico' => 
  array (
    0 => 
    array (
      'type' => 'file',
      'Controller' => 'E:\\www\\\\CcMvcProyect\\favicon.ico',
    ),
    1 => 1482370953,
  ),
  '/ccmvcproyect/src/images/ccmvc-peque.png?GDw=30COOKIE1024' => 
  array (
    0 => 
    array (
      'type' => 'file',
      'Controller' => 'E:\\www\\CcMvcProyect\\src\\images\\CcMvc-peque.png',
      'RealFile' => 'E:\\www\\CcMvcProyect\\protected\\Cache\\ImageGD\\w30h30csrc.images.CcMvc-peque.png',
      'GDmaxW' => '1024',
    ),
    1 => 1482785314,
  ),
  '/ccmvcproyect/src/images/ccmvc-peque.png?GDw=50COOKIE1024' => 
  array (
    0 => 
    array (
      'type' => 'file',
      'Controller' => 'E:\\www\\CcMvcProyect\\src\\images\\CcMvc-peque.png',
      'RealFile' => 'E:\\www\\CcMvcProyect\\protected\\Cache\\ImageGD\\w50h50csrc.images.CcMvc-peque.png',
      'GDmaxW' => '1024',
    ),
    1 => 1482511974,
  ),
  '/ccmvcproyect/src/js/jquery-3.1.0.min.js' => 
  array (
    0 => 
    array (
      'type' => 'file',
      'Controller' => 'E:\\www\\CcMvcProyect\\src\\js\\jquery-3.1.0.min.js',
    ),
    1 => 1482785313,
  ),
  'AutoloadCore' => 
  array (
    0 => 
    array (
      'Cc\\Mvc\\Cindex' => 'E:\\www\\CcMvcProyect\\protected\\controllers\\Cindex.php',
      'Smarty_Internal_Data' => 'E:\\www\\CcMvc\\libs\\smarty-3.1.30\\libs\\sysplugins\\smarty_internal_data.php',
      'Smarty' => 'E:\\www\\CcMvc\\libs\\smarty-3.1.30\\libs\\Smarty.class.php',
      'Smarty_Internal_Method_AssignGlobal' => 'E:\\www\\CcMvc\\libs\\smarty-3.1.30\\libs\\sysplugins\\smarty_internal_method_assignglobal.php',
      'Smarty_Internal_Method_ClearAllAssign' => 'E:\\www\\CcMvc\\libs\\smarty-3.1.30\\libs\\sysplugins\\smarty_internal_method_clearallassign.php',
      'Smarty_Internal_Resource_File' => 'E:\\www\\CcMvc\\libs\\smarty-3.1.30\\libs\\sysplugins\\smarty_internal_resource_file.php',
      'Smarty_Template_Compiled' => 'E:\\www\\CcMvc\\libs\\smarty-3.1.30\\libs\\sysplugins\\smarty_template_compiled.php',
      'MatthiasMullie\\Minify\\Minify' => 'E:\\www\\CcMvc\\libs\\minify-master\\src\\Minify.php',
      'MatthiasMullie\\Minify\\JS' => 'E:\\www\\CcMvc\\libs\\minify-master\\src\\JS.php',
      'MatthiasMullie\\Minify\\CSS' => 'E:\\www\\CcMvc\\libs\\minify-master\\src\\CSS.php',
      'MatthiasMullie\\PathConverter\\Converter' => 'E:\\www\\CcMvc\\libs\\minify-master\\src\\path-converter-master\\src\\Converter.php',
    ),
    1 => 1483494979,
  ),
);?>